name: Testing CI
on:
  push:
    branches:
      - master
    paths-ignore:
      - "README.md"
  pull_request:
    paths-ignore:
      - "README.md"

permissions:
  contents: read
  
concurrency:
  group: ${{ github.workflow_ref }}
  cancel-in-progress: true

jobs:
  frontend:
    name: Frontend
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Build with yarn
        uses: garnercorp/build-actions/yarn@change-yarn-action
